// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ArtemisBlog
{
    internal sealed partial class Vsix
    {
        public const string Id = "a2b9575b-b0f2-417c-952f-42a5b95984b9";
        public const string Name = "Artemis Blog";
        public const string Description = @"Displays entries from NASA's Artemis mission blog.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Andrew Rowe";
        public const string Tags = "nasa,rss,artemis";
    }
}
